name: splithome
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sign_in_with_apple: ^7.0.1
  supabase_flutter: 2.9.1
  share_plus: ^11.1.0
  intl: ^0.18.1
  local_auth: ^2.1.6
  fl_chart: ^0.68.0
  pdf: ^3.10.1
  printing: ^5.11.0
  path_provider: ^2.0.14





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:
  uses-material-design: true
